//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pollresponse
    {
        public int C_id { get; set; }
        public int pollid { get; set; }
        public int optionid { get; set; }
        public Nullable<int> ResponseCount { get; set; }
    
        public virtual PollOption PollOption { get; set; }
        public virtual Poll Poll { get; set; }
    }
}
