//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class polldbEntities : DbContext
    {
        public polldbEntities()
            : base("name=polldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PollOption> PollOptions { get; set; }
        public virtual DbSet<pollresponse> pollresponses { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
